 %%% Function made to write a nordic file
% Input:    EVENT > structure generated by read_nor
%           outputfile > nordic output file

function write_nor(EVENT,outputfile)

% %%%% Load structure
% 
% A=load('collect.mat');
% EVENT=A.EVENT;

%%%% Give filenmane

file=outputfile;

fic=fopen(file,'wt');

for i=1:length(EVENT)
    clear sheader s7 s6 sF
    
    %%% Write header
    sheader=write_line(EVENT(i),1);
    fprintf(fic,'%s\n',sheader);
    
    %%% Write format F line
    if ~strcmp(EVENT(i).FOC,' ') & ~isempty(EVENT(i).FOC);
        sF=write_line(EVENT(i),'F');
        fprintf(fic,'%s\n',sF);
    end
    
    %%% Write format I line
    if ~isempty(EVENT(i).ID);
        sI=write_line(EVENT(i),'I');
        fprintf(fic,'%s\n',sI);
    end
    
    %%% Write format E line
    if ~isempty(EVENT(i).ERROR);
        sI=write_line(EVENT(i),'E');
        fprintf(fic,'%s\n',sI);
    end
    
    %%% Write format 6 line
    if ~strcmp(EVENT(i).WAV,' ');
        s6=write_line(EVENT(i),6);
        fprintf(fic,'%s\n',s6);
    end
    
    %%% Write format 7 line
    s7=write_line(EVENT(i),7);
    fprintf(fic,'%s\n',s7);

    %%% Write format 4 lines
    for j=1:length(EVENT(i).DATA)
        clear s4
        s4=write_line(EVENT(i).DATA(j),4);
        fprintf(fic,'%s\n',s4); 
    end
    
    %%% Write blank line to seperate EVENT
    fprintf(fic,'%80s\n',' ');
    
end

fclose(fic);
    
end

function string=write_line(datas,format)

%%% 2008 0601F0003 59.2 L -15.249 167.542 50.1FFVAN 12 0.3 1.8LVAN                1
%%% XXXX UUXXUXXUU UUUU X UUUUUUU XXXXXXXUUUUUXUXXXUUUXXXX UUUXUUU        
%%% 1    2 3 45 6  7    8 9       10      11   1213141516   17 1819  


%%% STAT SP IPHASW D HRMM SECON CODA AMPLIT PERI AZIMU VELO AIN AR TRES W  DIS CAZ7
%%% XXXXXUX UXXXXU X UUXX UUUUU XXXXUUUUUUU XXXX UUUUU XXXXUUUUXXXUUUUUXXUUUUU XXXU
%%% 1    23 45   6 7 8 9  10    11  12      13   14    15  16  17 18   1920    21 22     

% s=' XXXXXUX UXXXXU X UUXX UUUUU XXXXUUUUUUU XXXX UUUUU XXXXUUUUXXXUUUUUXXUUUUU XXXU';

%%%%%%%%
%%% Define Format
%%%%%%%%

%format_type1=[' %4.0f %2.0f%2.0f%c%02.0f%02.0f %4.1f %c %7.3f %7.3f%5.1f%c%c%.3s',...
%    '%3.0f%4.1f%4.1f %31c'];
%format_type4=' %-5s%c%c %c%-4s%s%s%s %2s%2s %5s %33s %5s%2s %4s %3s ';
format_type7='%s';
string_type7=[' STAT SP IPHASW D HRMM SECON CODA AMPLIT',...
    ' PERI AZIMU VELO AIN AR TRES W  DIS CAZ7'];


switch format
    case 1
        string=sprintf('%80s',' ');
        string(2:5)=sprintf('%4.0f',datas.year);
        string(7:8)=sprintf('%2.0f',datas.month);
        string(9:10)=sprintf('%2.0f',datas.day);
        string(11)=sprintf('%1s',datas.fixtime);
        string(12:13)=sprintf('%2.0f',datas.hour);
        string(14:15)=sprintf('%2.0f',datas.min);
        string(17:20)=sprintf('%4.1f',datas.sec);
        
        string(21)=sprintf('%1s',datas.modelindic);
        string(22)=sprintf('%1s',datas.distanceindic);
        string(24:30)=sprintf('%7s',num2str(datas.lat,'%7.3f'));
        string(32:38)=sprintf('%7s',num2str(datas.lon,'%7.3f'));
        string(39:43)=sprintf('%5s',num2str(datas.depth,'%5.1f'));
        string(44)=sprintf('%1s',datas.fixdepth);
        string(45)=sprintf('%1s',datas.fixepic);
        string(46:48)=sprintf('%3.3s',datas.agency);
        string(49:51)=sprintf('%3.3s',num2str(datas.numbersta,'%3.0f'));
        
        string(52:55)=sprintf('%4.4s',num2str(datas.rms,'%4.1f'));
        
        string(56:59)=sprintf('%4.4s',num2str(datas.mag,'%4.1f'));
        string(60)=sprintf('%1s',datas.typemag);
        string(61:63)=sprintf('%3.3s',datas.magagency);
        string(80)='1';
    case 'F'
        string=sprintf('%s',...
            datas.FOC);
    case 'I'
        string=sprintf('%80s',' ');
        string(58:75)=sprintf('ID:%-15s',datas.ID);
        string(80)='I';
    case 'E'
        string=sprintf('%80s',' ');
        string(25:30)=sprintf('%6s',num2str(datas.ERROR.y,'%6.1f'));
        string(33:38)=sprintf('%6s',num2str(datas.ERROR.x,'%6.1f'));
        string(39:43)=sprintf('%5s',num2str(datas.ERROR.z,'%5.1f'));
        string(80)='E';
    case 7
        string=sprintf(format_type7,...
            string_type7);
    case 6
        string=sprintf('%80s',' ');
        string(2:1+length(datas.WAV))=datas.WAV;
        string(80)='6';
    case 4
        string=sprintf('%80s',' ');
        string(2:6)=sprintf('%-5.5s',datas.station);
        string(7)=sprintf('%1.1s',datas.type);
        string(8)=sprintf('%1.1s',datas.component);
        string(10)=sprintf('%1.1s',datas.quality);
        string(11:14)=sprintf('%-4.4s',datas.phase);
        %datas.weight
        string(15)=sprintf('%1s',num2str(datas.weight,'%1.0f'));
        string(17)=sprintf('%1.1s',datas.firstmotion);
        string(19:28)=sprintf('%2.0f%2.0f %5.2f',datas.hour,datas.min,datas.sec);
        string(30:33)=sprintf('%4s',num2str(datas.coda,'%4.0f'));
        string(34:40)=sprintf('%7s',num2str(datas.amplitude,'%7.1e'));
        string(42:45)=sprintf('%4s',num2str(datas.period,'%4.2f'));
        string(47:51)=sprintf('%5s',num2str(datas.approach,'%5.0f'));
        string(53:56)=sprintf('%4s',num2str(datas.velocity,'%4.0f'));
        string(57:60)=sprintf('%4s',num2str(datas.incidence,'%4.0f'));
        string(61:63)=sprintf('%3s',num2str(datas.AR,'%3.0f'));
        string(64:68)=sprintf('%5.5s',num2str(datas.residual,'%5.4g'));
        string(69:70)=sprintf('%2s',num2str(datas.weightcal,'%2.0f'));
        string(71:79)=sprintf('%5.0f %3.0f',datas.distance,datas.azi);
        
%         string=sprintf(format_type4,...
%             datas.station,datas.type,datas.component,datas.quality,...
%             datas.phase,datas.weight,' ',datas.firstmotion,...
%             datas.hour,datas.min,datas.sec,' ',datas.residual,datas.weightcal,...
%             datas.distance,datas.azi);
    otherwise
        disp('wrong format specified');
end

end
            
function datas=numstru2stringstru(datas)

field=fieldnames(datas);
datas=struct2cell(datas);
ind=(cellfun(@(x) any(isfloat(x)),datas));
datas(ind)=cellfun(@(x) num2str(x,'%5.2f'),datas(ind),'UniformOutput',false);
datas=cell2struct(datas,field);

end



